### ISSUE TITLE
Change Private `_PascalCase` Fields to `_camelCase`

### ISSUE THREAD

**Issue by EBrown8534** [EBrown8534/Framework#5]
Title is self-explanatory, I have used `_PascalCase` all over the place for private fields, the goal is to make them `_camelCase`.

**Comment by retailcoder** [comment]
:+1:  Ctrl+R,R should be useful :wink:

**Comment by EBrown8534** [comment]
Completed with commit: https://github.com/EBrown8534/Framework/commit/925ec85f22795c920b73705eb601a758363cd3eb
